export const ContactFaq = [
  {
    id: 1,
    title: `How long does the whole appointment take?`,
    content: `About 45 minutes!`,
  },
  {
    id: 2,
    title: `What does the appointment entail?`,
    content: `At your MYndspan appointment, you’ll first spend 20 minutes on an iPad app. Here, we’ll ask you some
    background questions like age, biological sex and other questions that will give us some context to the
    brain activity we’ll measure. Also on the app you’ll complete some (fun!) gamified tasks that measure
    cognitive functions like short term memory, visuospatial skills and attention. After the 20 minutes on the
    iPad, you’ll get prepped for your brain scan where we take a 3D digitization of your head and get you
    situated in the scanner. This takes about 10 minutes. Then you sit for a completely passive 10 minute
    scan and try not to fall asleep! When that’s done, you’re good to go and your MYndspan report will be in
    your email within 24 hours.`,
  },
  {
    id: 3,
    title: `How long does it take to complete the cognitive games?`,
    content: `The games take approximately 15 minutes to complete, after completing about 5 minutes of general
    questions.`,
  },
  {
    id: 4,
    title: `What’s it like having a MEG scan?`,
    content: `You know those old-fashioned hair dryers? Kind of like that. MEG (magnetoencephalography) is a totally
    non-invasive technique that does not require any injections, and does not expose you to any radiation. It
    is simply a super sensitive sensor of magnetic fields. The magnetic fields from our brains are so small
    that we need to try and remove any magnetic fields created by other things like metal objects and
    electronics, so the MEG sits within a specific room that blocks out magnetic fields from the
    environment, and we will ask you to remove any metal/electronics before going into the room.`,
  },
  {
    id: 5,
    title: `Does the MEG scan have any side effects?`,
    content: `MEG scanning is completely non-invasive and painless. No applied gels, no noises, and you don’t even
    have to change clothes. There are no known side effects from MEG scanning.`,
  },
  {
    id: 6,
    title: `I get anxiety inside an MRI, how does the MEG scanner compare?`,
    content: [
      `Rather than laying down inside a very large and confining magnet, as you would for an MRI, you only
    need to place your head in a helmet to complete a MEG scan. This allows for a clear view of your
    surroundings at all times.
    Similar to an MRI, the MEG is in a separate room. Technicians will be next door to you, they will be able
    to see you at all times and you may communicate with them throughout the scan.`,
    ],
  },
  {
    id: 7,
    title: `Can I move inside the MEG?`,
    content: `To obtain accurate recordings, try to stay as still as possible.`,
  },
  {
    id: 8,
    title: `Can I close my eyes inside the MEG?`,
    content: `No, the brain generates very different activity when the eyes are open versus when the eyes are closed
    and because of this we require clients to keep their eyes open during the scan.`,
  },
  {
    id: 9,
    title: `Does the MEG scan have any side effects?`,
    content: `MEG scanning is completely non-invasive and painless. No applied gels, no noises, and you don’t even
    have to change clothes. There are no known side effects from MEG scanning.`,
  },
  {
    id: 10,
    title: `Does the MEG scanner sound like an MRI?`,
    content: `No, the MEG is completely silent – this is why we say the hardest part is not falling asleep!`,
  },
  {
    id: 11,
    title: `Will there be any gels, like those used for an EEG, placed on my scalp?`,
    content: `Nope, all you have to do is place your head in a helmet.`,
  },
  {
    id: 12,
    title: `Can anyone be in the same room with me while the scanning occurs?`,
    content: `We prefer that you are in the room alone in order to minimize the potential for interference. However,
    the comfort of our clients is always a top priority and this request can be accommodated.`,
  },
  {
    id: 13,
    title: `Is there anything I need to do to prepare for my visit?`,
    content: `Try to avoid caffeine or taking any non-prescription drugs that would affect your brain’s function. Also,
    wear clothing without metal and remove any jewellery prior to scanning. Metals interfere with the
    magnetic fields the MEG is attempting to measure. This is because moving metal generates a magnetic
    field that is much greater than the magnetic field generated by the neurons in your brain. It therefore
    prevents the scanner from analyzing the brain activity accurately.`,
  },
  {
    id: 14,
    title: `What can a MYndspan baseline scan do for me right now?`,
    content: `The report provides a snapshot of your brain activity at the time you had the scan. Each person has a
    unique pattern of naturally occurring brain activity, which tends to remain stable in the short term.
    Using your baseline as a reference, we can tell whether your brain activity is meaningfully different on a
    subsequent scan.`,
  },
  {
    id: 15,
    title: `What could a MYndspan baseline scan do for me in the future?`,
    content: `Your brain scan, stored in its raw form, contains an incredible wealth of data. As we continue to analyze
    data and develop our scientific analysis, we will build a better picture of what &quot;normal&quot; brain activity
    looks like. Newly discovered insights can be applied to any of your previous scans – when you look at it
    in this way, the value of your previous scans increases over time.`,
  },
  {
    id: 16,
    title: `What will the MYndspan report show me?`,
    content: `Your MYndspan report will give you a breakdown of your performance on the cognitive tasks, both
    relative to your comparative group, and compared to yourself over time. It will also provide an analysis
    
    of your brainwaves and the activity measured in your main brain networks. For illustrative purposes and
    for context, we sometimes plot these measures against our normative database, however, how you
    compare is not meaningful. What is meaningful is how your own brain changes over time – you
    compared to yourself. Which is why we say it’s important to come back and monitor your brain over
    time.`,
  },
  {
    id: 17,
    title: `Does it matter how I compared to the norm?`,
    content: `No! That seems counterintuitive, but brains are so unique it’s like everyone’s brain is their own
    distinctive finger print or QR code. It’s not like one fingerprint is bad and another is good – same with
    the brain. So for instance, how much activity you have in your brain networks isn’t meaningful in and of
    itself. What is meaningful is how that activity changes, like the direction and speed of change. This is
    why we say it’s important to come back and monitor your brain over time. And to have a healthy
    baseline with which to make future comparisons.`,
  },
  {
    id: 18,
    title: `Why is it important to measure my brain’s function when I haven’t had any injuries?`,
    content: `Obtaining a measurement when you haven’t had injuries allows us to monitor your brain’s function and
    detect changes over time. This could enable the early identification of cognitive decline and allow for
    treatment at early stages. If specific incident occurs, having a baseline measure can help measure the
    severity of these injuries.`,
  },
  {
    id: 19,
    title: `Can I come back to monitor my brain’s function over time?`,
    content: `Yes! We recommend completing periodic follow-up visits to examine how your brain changes over time,
    and to measure how you respond to injuries and treatments.`,
  },
  {
    id: 20,
    title: `I have already injured my head, is it pointless for me to visit?`,
    content: `No. Obtaining a baseline measurement is useful at any time. Responses to head injuries and their
    treatments are unique. Furthermore, effects can be felt for years, and the impact of future injuries is
    likely to be even more severe. Measuring your brain’s activity at any time`,
  },
  {
    id: 21,
    title: `What is the brain scanner you use called?`,
    content: `Magnetoencephalography or MEG for short. It is a scanner that detects and records magnetic fields
    generated by the neurons in your brain with millisecond and millimetre accuracy – or as the science guys
    say, with unrivaled spatial and temporal resolution.`,
  },
  {
    id: 22,
    title: `What information does the brain scanner (MEG or magnetoencephalography) collect?`,
    content: `The MEG measures the magnetic fields naturally produced by your brain and it measures this with
    millisecond and millimetre accuracy. This allows us to identify areas of your brain that are active, the
    timing of that activity, and the type of brain waves produced by your brain. This gives us the incredibility
    ability to create incredibly powerful and detailed brain maps at an individual level. This data is analysed
    to describe your brain function.`,
  },
  {
    id: 23,
    title: `Will be my data be shared with anyone?`,
    content: `No, MYndspan will not share your data with any third party.`,
  },
  {
    id: 24,
    title: `Is my data secure?`,
    content: `In one word, Yes! MYndspan uses the latest cyber techniques to ensure that your data is transmitted to
    our cloud securely, and that it is stored there entirely anonymously. We use medical-grade encryption
    techniques and follow strict regulatory frameworks to ensure this.`,
  },
  {
    id: 25,
    title: `How does MEG compare to MRI?`,
    content: `Magnetic resonance imaging (MRI) is a medical imaging technique used to form pictures of the anatomy
    and the physiological processes of the body. MRI scanners applies strong magnetic fields, magnetic field
    gradients, and radio waves to generate images of the organs in the body. Because of it’s use of magnets
    to image the body, some patients with certain types of implants are not able to have an MRI scan.
    However similar to CT, MRIs creates a structural image of the brain. Comparatively, MEG doesn’t
    capture an image of the brain, but rather records how the brain is functioning.`,
  },
  {
    id: 26,
    title: `How does MEG compare to FMRI?`,
    content: `Functional magnetic resonance imaging or functional MRI (fMRI) measures brain activity by detecting
    changes associated with blood flow within the brain. The difference between these two techniques
    predominantly lies in that fMRI measures blood flow relying on the fact that cerebral blood flow and
    neuronal activation are coupled. MEG directly measures brain activity through the magnetic field the
    neuronal activation produces. Consequently, MEG allows the timing of brain activity to be measured
    more precisely, or scientifically, has a much higher temporal resolution than fMRI.`,
  },
  {
    id: 27,
    title: `How does MEG compare to EEG?`,
    content: `Similar to MEG, EEG measures and records electrical activity in the brain. However, unlike EEG, MEG can
    tell where in the brain this functional activity originates. This is because the human skull and the tissue
    surrounding the brain distort the electrical signals an EEG picks up, but affects magnetic fields produced
    by those electric signals much less and in a measurable way that can be accounted for. Consequently,
    MEG allows the location of brain activity to be measured far more precisely, or scientifically, has a much
    higher spatial resolution than EEG.`,
  },
  {
    id: 28,
    title: `How does MEG compare to CT?`,
    content: `A computerized tomography (CT) scan combines a series of X-ray images taken from different angles
    around your body and uses computer processing to create cross-sectional images of the bones, blood
    vessels and soft tissues inside your body. A CT scan is a standard imaging modality used to assess the
    brain. However, because it only creates a structural image of the brain. Comparatively, MEG doesn’t
    capture an image of the brain, but rather records how the brain is functioning. MEG is also completely
    non-invasive and does not require the use of radiation to detect brain function.`,
  },
  {
    id: 29,
    title: `How does MEG compare to SPECT/PET?`,
    content: `A single photon emission computed tomography (SPECT) scan and a positron emission tomography
    (PET) are imaging modalities that show how blood flows to tissues and organs. Both are nuclear imaging
    scans that integrates computed tomography (CT) and a radioactive tracer. The tracer is what allows
    doctors to see how blood flows to tissues and organs. Before the scan, a tracer is injected into the
    bloodstream. This imaging technique is used to form a 3D image of the brain. Comparatively, MEG
    doesn’t capture an image of the brain, but rather records how the brain is functioning. MEG is also
    completely non-invasive and does not require any tracer, radioactive or otherwise, to be injected.`,
  },
];
